// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9PTVTqz70OHQT_-2IMEztlG0xj6wQjUw',
    appId: '1:69136723572:web:9ad563be64782e171d6b21',
    messagingSenderId: '69136723572',
    projectId: 'presence-8c989',
    authDomain: 'presence-8c989.firebaseapp.com',
    storageBucket: 'presence-8c989.appspot.com',
    measurementId: 'G-42HLRC1TY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEwYeDgekWnpa_zxXPCYisuBWjx_ScZi4',
    appId: '1:69136723572:android:b7af150f3f52efdf1d6b21',
    messagingSenderId: '69136723572',
    projectId: 'presence-8c989',
    storageBucket: 'presence-8c989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUOpIlVIQC8NJ2LKEt4OVAbr6UN2F0ofo',
    appId: '1:69136723572:ios:3b159928150e29531d6b21',
    messagingSenderId: '69136723572',
    projectId: 'presence-8c989',
    storageBucket: 'presence-8c989.appspot.com',
    iosBundleId: 'com.ichaproject.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUOpIlVIQC8NJ2LKEt4OVAbr6UN2F0ofo',
    appId: '1:69136723572:ios:3b159928150e29531d6b21',
    messagingSenderId: '69136723572',
    projectId: 'presence-8c989',
    storageBucket: 'presence-8c989.appspot.com',
    iosBundleId: 'com.ichaproject.presence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9PTVTqz70OHQT_-2IMEztlG0xj6wQjUw',
    appId: '1:69136723572:web:277e959ddb920ca41d6b21',
    messagingSenderId: '69136723572',
    projectId: 'presence-8c989',
    authDomain: 'presence-8c989.firebaseapp.com',
    storageBucket: 'presence-8c989.appspot.com',
    measurementId: 'G-QBQYB04T5P',
  );
}
